library/book_library/urls.py
from django.urls import path
from . import views

app_name = 'library'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    # Login urls
    path('login/', views.UserLogin.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.UserRegister.as_view(), name='register'),
    # Book urls
    path('books/', views.BookList.as_view(), name='book_list'),
    path('books/<int:pk>', views.BookDetail.as_view(), name="book_detail"),
    path('books/create', views.BookCreate.as_view(), name='book_create'),
    path('books/update/<int:pk>', views.BookFormUpdate.as_view(), name='book_update'),
    path('books/delete/<int:pk>', views.BookDelete.as_view(), name='book_delete'),
    # Author urls
    path('authors/', views.AuthorList.as_view(), name="author_list"),
    path('authors/<int:pk>', views.AuthorDetail.as_view(), name="author_detail"),
    path('authors/create', views.AuthorCreate.as_view(), name='author_create'),
    path('authors/update/<int:pk>', views.AuthorUpdate.as_view(), name='author_update'),
    path('authors/delete/<int:pk>', views.AuthorDelete.as_view(), name='author_delete'),
    # Category urls
    path('categories/', views.CategoryList.as_view(), name="category_list"),
    path('categories/<int:pk>', views.CategoryDetail.as_view(), name="category_detail"),
    path('categories/create', views.CategoryCreate.as_view(), name='category_create'),
    path('categories/update/<int:pk>', views.CategoryUpdate.as_view(), name='category_update'),
    path('categories/delete/<int:pk>', views.CategoryDelete.as_view(), name='category_delete'),
    # Statistic urls
    path('statistics/', views.DateStatistic.as_view(), name='date_statistic')
    ]

library/library/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('book_library.urls')),
    path('api/', include('book_library_api.urls')),
    path('admin/', admin.site.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/book_library/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('library:category_list')


class Book(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    written_at = models.DateTimeField()
    description = models.CharField(max_length=500)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('library:book_list')


class Author(models.Model):
    book = models.ManyToManyField(Book, blank=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    birth_date = models.DateField()
    created_at = models.DateTimeField(auto_now=True)
    author_pic = models.ImageField(
        default='media/default-profile-picture-gmail-2.png',
        upload_to='author_pictures')

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_absolute_url(self):
        return reverse('library:author_list')

library/book_library/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import Book, Author, Category


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username']


class BookForm(forms.ModelForm):
    authors = forms.ModelMultipleChoiceField(queryset=Author.objects.all())

    class Meta:
        model = Book
        fields = ['category', 'title', 'written_at', 'description', 'authors']

    def save(self, *args, **kwargs):
        data = self.cleaned_data
        book = super().save(commit=True)
        for author in data['authors']:
            book.author_set.add(author)
        return book


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['author_pic', 'book', 'first_name', 'last_name', 'birth_date']


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['title']

library/book_library/views.py
from .models import Book, Category, Author
from django.views import generic
from django.urls import reverse_lazy
from book_library import forms
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from .mixins import LoginRequiredNoNextMixin, StaffUserOnlyMixin
from django.db.models import Min, Max, Avg, Func, F, FloatField, DateField


# Create your views here.
class IndexView(LoginRequiredNoNextMixin, generic.base.TemplateView):
    template_name = 'library/index.html'


# Auth views
class LogoutView(generic.RedirectView):
    url = reverse_lazy('library:login')

    def get_redirect_url(self, *args, **kwargs):
        logout(self.request)
        return super().get_redirect_url(*args, **kwargs)


class UserLogin(LoginView):
    redirect_field_name = ''
    redirect_authenticated_user = True
    authentication_form = forms.LoginForm


class UserRegister(generic.CreateView):
    form_class = forms.RegistrationForm
    template_name = 'registration/register.html'
    success_url = '/login'


# Book Views
class BookDetail(LoginRequiredNoNextMixin, generic.DetailView):
    model = Book
    template_name = 'library/book_detail.html'


class BookList(LoginRequiredNoNextMixin, generic.ListView):
    model = Book
    template_name = 'library/books.html'
    paginate_by = 10
    queryset = Book.objects.all().order_by('pk')


class BookCreate(LoginRequiredNoNextMixin, StaffUserOnlyMixin, generic.CreateView):
    model = Book
    form_class = forms.BookForm
    template_name = 'library/model_edit.html'


class BookFormUpdate(LoginRequiredNoNextMixin, StaffUserOnlyMixin, generic.UpdateView):
    model = Book
    form_class = forms.BookForm
    template_name = 'library/model_edit.html'
    success_url = reverse_lazy('library:book_list')


class BookDelete(LoginRequiredNoNextMixin, StaffUserOnlyMixin, generic.DeleteView):
    model = Book
    template_name = 'library/book_confirm_delete.html'
    success_url = reverse_lazy('library:book_list')


# Author Views
class AuthorDetail(LoginRequiredNoNextMixin, generic.DetailView):
    model = Author
    template_name = 'library/author_detail.html'


class AuthorList(LoginRequiredNoNextMixin, generic.ListView):
    model = Author
    template_name = 'library/authors.html'
    paginate_by = 10
    queryset = Author.objects.all().order_by('pk')


class AuthorCreate(LoginRequiredNoNextMixin, StaffUserOnlyMixin, generic.CreateView):
    model = Author
    form_class = forms.AuthorForm
    template_name = 'library/model_edit.html'


class AuthorUpdate(LoginRequiredNoNextMixin, StaffUserOnlyMixin, generic.UpdateView):
    model = Author
    form_class = forms.AuthorForm
    template_name = 'library/model_edit.html'


class AuthorDelete(LoginRequiredNoNextMixin, StaffUserOnlyMixin, generic.DeleteView):
    model = Author
    template_name = 'library/author_confirm_delete.html'
    success_url = reverse_lazy('library:author_list')


# Category Views
class CategoryDetail(LoginRequiredNoNextMixin, generic.DetailView):
    model = Category
    template_name = 'library/category_detail.html'


class CategoryList(LoginRequiredNoNextMixin, generic.ListView):
    model = Category
    template_name = 'library/categories.html'
    paginate_by = 10
    queryset = Category.objects.all().order_by('pk')


class CategoryCreate(LoginRequiredNoNextMixin, StaffUserOnlyMixin, generic.CreateView):
    model = Category
    form_class = forms.CategoryForm
    template_name = 'library/model_edit.html'


class CategoryUpdate(LoginRequiredNoNextMixin, StaffUserOnlyMixin, generic.UpdateView):
    model = Category
    form_class = forms.CategoryForm
    template_name = 'library/model_edit.html'


class CategoryDelete(LoginRequiredNoNextMixin, StaffUserOnlyMixin, generic.DeleteView):
    model = Category
    template_name = 'library/category_confirm_delete.html'
    success_url = reverse_lazy('library:category_list')


# Statistic Views
class DateStatistic(LoginRequiredNoNextMixin, generic.TemplateView):
    template_name = 'library/date_statistics.html'
    context_object_name = 'dates'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['authors_dates'] = Author.objects.aggregate(
            min_date=Min('birth_date'),
            max_date=Max('birth_date'),
            avg_date=Func(
                Avg(
                    Func(
                        F('birth_date'), function='JULIANDAY', output_field=FloatField()
                        )
                    ), function='DATE', output_field=DateField()))
        context['books_dates'] = Book.objects.aggregate(
            min_date=Min('written_at'),
            max_date=Max('written_at'))
        return context

library/book_library/templates/library/author_confirm_delete.html
{% extends "library/layout.html" %}

{% block title %}
    Potvrďte smazání
{% endblock title %}

{% block content %}
<form method="POST" action="{% url 'library:author_delete' object.id %}">
    {% csrf_token %}
    <p>Opravdu chcete smazat autora {{object}}?</p>
    <input type="submit" value="Smazat">
</form>  
{% endblock content %}

library/book_library/templates/library/author_detail.html
{% extends "library/layout.html" %}

{% block title %}
{{ author.last_name }}
{% endblock title %}

{% block content %}
<img src="{{author.author_pic.url}}" height="200" width="200">
<h2>Křestní jméno:</h2> <p>{{author.first_name}}</p>
<h2>Příjmení:</h2> <p>{{author.last_name}}</p>
<h2>Datum narození:</h2> <p>{{author.birth_date}}</p>
{% endblock content %}

library/book_library/templates/library/authors.html
{% extends "library/layout.html" %}

{% block title %}Autoři{% endblock title %}

{% block content %}

{% if user.is_staff %}
<a href="{% url 'library:author_create' %}">Vytvořit autora</a>  
{% endif %}

<table>
    <tr>
        <th>Křestní jméno</th>
        <th>Příjmení</th>
        <th>Datum narození</th>
    </tr>
    {% for author in author_list %}
    <tr>
        <td>{{author.first_name}}</td>
        <td>{{author.last_name}}</td>
        <td>{{author.birth_date}}</td>
        <td><a href="{% url 'library:author_detail' author.id %}">Detail autora</a></td>
        {% if user.is_staff %}
        <td><a href="{% url 'library:author_update' author.id %}">Editovat</a></td>
        <td><a href="{% url 'library:author_delete' author.id %}">Smazat</a></td>  
        {% endif %}
    </tr>
    {% endfor %}
</table>
{% include "library/pagination_template.html" with objects=author_list %}
{% endblock content %}

library/book_library/templates/library/book_confirm_delete.html
{% extends "library/layout.html" %}

{% block title %}
  Potvrďte smazání
{% endblock title %}

{% block content %}
<form method="POST" action="{% url 'library:book_delete' object.id %}">
    {% csrf_token %}
    <p>Opravdu chcete smazat "{{ object }}"?</p>
    <input type="submit" value="Smazat">
</form>  
{% endblock content %}

library/book_library/templates/library/book_detail.html
{% extends "library/layout.html" %}

{% block title %}
{{book.title}}  
{% endblock title %}

{% block content %}
<h2>Název:</h2> <p>{{ book.title }}</p>
<h2>Popis:</h2> <p>{{ book.description }}</p>
<h2>Datum napsání knihy:</h2> <p>{{ book.written_at }}</p>
<h2>Kategorie:</h2> <p>{{ book.category }}</p>  
{% endblock content %}

library/book_library/templates/library/books.html
{% extends "library/layout.html" %}

{% block title %}Knihy{% endblock title %}

{% block content %}
{% if user.is_staff %}
<a href="{% url 'library:book_create' %}">Vytvořit knihu</a>  
{% endif %}
<table>
    <tr>
        <th>Kategorie</th>
        <th>Název</th>
        <th>Datum napsání knihy</th>
        <th>Popis</th>
        <th>Detail Knihy</th>
    </tr>
    {% for book in book_list %}
    <tr>
        <td><a href="{% url 'library:category_detail' book.category.id %}">{{ book.category }}</a></td>
        <td>{{ book.title }}</td>
        <td>{{ book.written_at }}</td>
        <td>{{ book.description }}</td>
        <td><a href="{% url 'library:book_detail' book.id %}">Detail knihy</a></td>
        {% if user.is_staff %}
        <td><a href="{% url 'library:book_update' book.id %}">Editovat</a></td>
        <td><a href="{% url 'library:book_delete' book.id%}">Smazat</a></td>
        {% endif %}
    </tr>
    {% endfor %}
</table>
{% include "library/pagination_template.html" with objects=book_list %}
{% endblock content %}

library/book_library/templates/library/categories.html
{% extends "library/layout.html" %}

{% block title %}Kategorie{% endblock title %}

{% block content %}

{% if user.is_staff %}
<a href="{% url 'library:category_create' %}">Vytvořit kategorii</a>
{% endif %}

<table>
    <tr>
        <th>Název</th>
    </tr>
    {% for category in category_list %}
    <tr>
        <td><a href="{% url 'library:category_detail' category.id%}">{{ category.title }}</a></td>
        {% if user.is_staff %}
        <td><a href="{% url 'library:category_update' category.id%}">Editovat</a></td>
        <td><a href="{% url 'library:category_delete' category.id %}">Smazat</a></td>
        {% endif %}
    </tr>
    {% endfor %}
</table>
{% include "library/pagination_template.html" with objects=category_list %}
{% endblock content %}

library/book_library/templates/library/category_confirm_delete.html
{% extends "library/layout.html" %}

{% block title %}
    Potvrďte smazání
{% endblock title %}

{% block content %}
    <form method="POST" action="{% url 'library:category_delete' object.id %}">
        {% csrf_token %}
        <p>Opravdu chcete smazat {{object}}?</p>
        <input type="submit" value="Smazat">
    </form>
{% endblock content %}
    

library/book_library/templates/library/category_detail.html
{% extends "library/layout.html" %}

{% block title %}Kategorie{% endblock title %}
{% block content %}
<h2>Název:</h2> <p>{{ category.title }}</p>  
{% endblock content %}

library/book_library/templates/library/date_statistics.html
<ul>
    <li><p>Nejmenší datum narození: {{authors_dates.min_date}}</p></li>
    <li><p>Největší datum narození: {{authors_dates.max_date}}</p></li>
    <li><p>Průměr dat narození: {{authors_dates.avg_date}}</p></li>
    <li><p>Nejmenší datum napsané knihy: {{books_dates.min_date}}</p></li>
    <li><p>Největší datum napsané knihy: {{books_dates.max_date}}</p></li>
</ul>

library/book_library/templates/library/index.html
{% extends "library/layout.html" %}

{% block title%}Hlavní stránka{% endblock %}
{% block content %}
<h1>Vítejte v rejstříku knih</h1>
<ul>
    <li>
        <a href="{% url 'library:book_list' %}">Knihy</a>
    </li>
    <li>
        <a href="{% url 'library:author_list' %}">Autoři</a>
    </li>
    <li>
        <a href="{% url 'library:category_list' %}">Kategorie</a>
    </li>
</ul>
  
{% endblock content %}

library/book_library/templates/library/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Rejstřík knih{% endblock %}</title>
</head>
<body>
    <header>
        <h1>Rejstřík knih</h1>
        <div id="logout"><a href="{% url 'library:logout' %}">Odhlásit se</a></div>
        <a href="{% url 'library:book_list' %}">Knihy</a>
        <a href="{% url 'library:author_list' %}">Autoři</a>
        <a href="{% url 'library:category_list' %}">Kategorie</a>
    </header>
    {% block content %}
    {% endblock %}
</body>
</html>

library/book_library/templates/library/model_edit.html
{% extends "library/layout.html" %}

{% block title %}
Editovat knihu
{% endblock title %}

{% block content %}
<form method="POST" action="" enctype="multipart/form-data"> {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>  
{% endblock content %}

library/book_library/templates/library/pagination_template.html
<p>Pages:</p>
{% for i in paginator.page_range %}
    {% if objects.number == i %}
        {{ i }}
    {% else %}
        <a href="?page={{ i }}">{{ i }}</a>
    {% endif %}
{% endfor %}